### ISSUE TITLE
duply_backup_jobs syntax

### ISSUE THREAD

**Issue by sajadonline** [Oefenweb/ansible-duply-backup#22]
how can use duply_backup_jobs syntax in variable ? Every mode I write gives an error.

‍ - role:
       ansible-duply-backup
      vars:
        
        duply_backup_jobs:
            cron.name: test-backup
            cron.minute: 5

**Comment by tersmitten** [comment]
I hope this is useful for you. This is the configuration we're using to backup a "wordress server":

```yml
# duply-backup role variables
---
duply_backup_default_max_age: 1M
duply_backup_default_max_fullbkp_age: 1W

duply_backup_profiles:
  var-www:
    conf:
      gpg_key: "{{ duply_backup_default_gpg_key }}"
      gpg_pw: "{{ duply_backup_default_gpg_pw }}"
      gpg_key_sign: "{{ duply_backup_default_gpg_pw_sign }}"
      gpg_pw_sign: "{{ duply_backup_default_gpg_pw }}"
      gpg_opts: "{{ duply_backup_default_gpg_opts }}"

      target: "{{ duply_backup_default_target }}/var-www"
      source: /var/www
      arch_dir: "{{ duply_backup_default_arch_dir }}"

      max_age: "{{ duply_backup_default_max_age }}"
      max_fullbkp_age: "{{ duply_backup_default_max_fullbkp_age }}"

      verbosity: "{{ duply_backup_default_verbosity }}"
    excludes:
      - '+ /var/www/*/*/public_html'
      - '- **'
  mydumper:
    conf:
      gpg_key: "{{ duply_backup_default_gpg_key }}"
      gpg_pw: "{{ duply_backup_default_gpg_pw }}"
      gpg_key_sign: "{{ duply_backup_default_gpg_pw_sign }}"
      gpg_pw_sign: "{{ duply_backup_default_gpg_pw }}"
      gpg_opts: "{{ duply_backup_default_gpg_opts }}"

      target: "{{ duply_backup_default_target }}/mydumper"
      source: "{{ mydumper_backup_backup_path }}"
      arch_dir: "{{ duply_backup_default_arch_dir }}"

      max_age: "{{ duply_backup_default_max_age }}"
      max_fullbkp_age: "{{ duply_backup_default_max_fullbkp_age }}"

      verbosity: "{{ duply_backup_default_verbosity }}"
    pre: "{{ playbook_dir }}/files/duply-backup/scripts/mydumper/keep-last/pre"
    post: "{{ playbook_dir }}/files/duply-backup/scripts/mydumper/keep-last/post"

duply_backup_jobs:
  - name: "duply-backup-var-www"
    job: "/usr/local/bin/duply var-www pre+[bkp-verify]+post+purge --force"
    minute: 0
    hour: 0
  - name: "duply-backup-mydumper"
    job: "/usr/local/bin/duply mydumper pre+[bkp-verify]+post+purge --force"
    minute: 0
    hour: 0

```
